# Generated by Django 3.2.8 on 2021-10-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='file_html',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_text',
            field=models.FileField(blank=True, null=True, upload_to='html/text'),
        ),
    ]
